name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # Or your primary branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main # Or your primary branch

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_STONE_065D94E0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # --- START OF DEFINITIVE FIX ---
          # This configuration tells Azure how to build a Vite project correctly
          app_location: "/" # The root of your repository
          api_location: "api" # The location of your Azure Functions
          output_location: "dist" # The build output folder for Vite
          # --- END OF DEFINITIVE FIX ---
        env:
          CI: false # Prevents warnings from being treated as errors

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_STONE_065D94E0F }}
          action: "close"
